model:
    arch: pspnet
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    #img_rows: 'same'
    #img_cols: 'same'
    img_rows: 512
    img_cols: 1024
    path: /home/kollmitz/datasets/PASCAL_VOC/VOCdevkit/VOC2012/
    sbd_path: /home/kollmitz/datasets/PASCAL_VOC/benchmark_RELEASE/
training:
    n_workers: 1
    train_iters: 500
    batch_size: 2 # batch size > 1 needs img_rows and img_cols specified, <1 not working
    val_interval: 500
    print_interval: 25
    
    #optimizer configuration
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule: 
    resume: pspnet_pascal_best_model.pkl
